inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - "**/*.erb"
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'vendor/**/*'

Layout/LineLength:
  IgnoredPatterns: ['^Given', '^When', '^Then', '^And']
    - 'config/*'
