---
inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

plugins: rubocop-performance

AllCops:
  TargetRubyVersion: 3.3.9

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either
