version: "3.8"

volumes:
  db_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghrc.io/dfe-digital/help-for-early-years-providers:develop
    command: ./entrypoints/docker-entrypoint.sh
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env

  database:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file: .env