# ------------------------------------------------------------------------------
#
#
---
services:
  app:
    container_name: reform_prod
    build:
      context: .
      target: app
    image: reform:prod
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - EDITOR=vi
      - RAILS_ENV=production
      - NODE_ENV=production
      - WEB_CONCURRENCY=0
      - PROXY_CERT
    networks:
      - reform

  db:
    container_name: reform_db
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - reform

volumes:
  db:

networks:
  reform:
