---
services:
  app:
    container_name: reform_test
    build:
      target: test
    image: reform:test
    environment:
      - RAILS_ENV=test
      - DOMAIN=reform.app
      - DEBUG=false
      - CONTENTFUL_MANAGEMENT_TOKEN=
    tty: true
    stdin_open: true
