# ------------------------------------------------------------------------
#
#
---
version: '3.8'
services:
  app:
    container_name: hfeyp_prod
    build:
      context: .
      target: app
    image: hfeyp:prod
    command: rails server -b 0.0.0.0
    environment:
      - EDITOR=vi
      - RAILS_ENV=production
      - NODE_ENV=production
      - RAILS_MASTER_KEY
      - RAILS_LOG_TO_STDOUT
      - WEB_CONCURRENCY=0
      - PROXY_CERT
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - hfeyp

  db:
    container_name: hfeyp_db
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - hfeyp

volumes:
  db:

networks:
  hfeyp:
