# ------------------------------------------------------------------------------
#
#
---
services:
  app:
    container_name: reform_prod
    build:
      context: .
      target: app
    image: reform:prod
    ports:
      - 3000:3000
    environment:
      - EDITOR=vi
      - RAILS_ENV=production
      - NODE_ENV=production
      - WEB_CONCURRENCY=0
      - PROXY_CERT
    networks:
      - reform

networks:
  reform:
