version: "3.8"

volumes:
  db_data:

services:
  app:
    build: .
    image: eyfs-reform-spike-web:latest
    command: ./entrypoints/docker-entrypoint.sh
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:13.1
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  webpack:
    image: eyfs-reform-spike-web:latest
    command: sh -c "npm rebuild node-sass && ./bin/webpack-dev-server"
    depends_on:
      - app
    volumes:
      - .:/app
    ports:
      - '3035:3035'
    env_file: .env
