---
RACK_ENV: production
RAILS_ENV: production
NODE_ENV: production
RAILS_LOG_TO_STDOUT: true
RAILS_MAX_THREADS: 5
RAILS_SERVE_STATIC_FILES: true
SERVICE_TYPE: web
DATABASE_URL: postgres://postgres@localhost:5432
DATABASE_NAME: eyfs-prod-database
FEEDBACK_URL: https://forms.office.com/Pages/ResponsePage.aspx?id=yXfS-grGoU2187O4s0qC-e5vHvNwH1tNvj-UhV9eyZZUM1pQNEtCN0YyVVdFVkpOUVNXNUlZNTdOUC4u
