name: 'App Deploy [Azure - REVIEW TEARDOWN]'

on:
  pull_request:
    types:
      - closed

# Permissions for OIDC authentication
permissions:
  id-token: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  DOCKER_IMAGE: ghcr.io/dfe-digital/help-for-early-years-providers
  PR_NUMBER: pr-${{ github.event.number }}

jobs:
  teardown:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Login to Azure using OIDC
      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Destroy Web Application
      - name: Destroy Azure Web Application
        uses: azure/CLI@v2
        with:
          azcliversion: 2.50.0
          inlineScript: |
            az webapp deployment slot delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ vars.REVIEWAPP_NAME }} \
              --slot ${{ env.PR_NUMBER }}
            az postgres flexible-server db delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --server-name ${{ vars.RESOURCE_NAME_PREFIX }}-psqlfs \
              --database-name ${{ env.PR_NUMBER }} \
              --yes
