name: Build and Deploy to Sandbox

on:
  push:
    branches:
      - develop
      paths-ignore:
        - 'documentation/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: softprops/turnstyle@v1
        name: Check workflow concurrency
        with:
          poll-interval-seconds: 20
          same-branch-only: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        name: Checkout Code

      - name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.14.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            SHA=${{ github.sha }}
          cache-from: |
            dfedigital/help-for-early-years-providers-sandbox:latest
          push: true
          tags: |
            dfedigital/help-for-early-years-providers-sandbox:${{ github.sha }}
            dfedigital/help-for-early-years-providers-sandbox:latest
          target:
            sandbox

      - name: Deploy to sandbox
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_paas_user: ${{ secrets.GOVPAAS_SANDBOX_USERNAME }}
          TF_VAR_paas_password: ${{ secrets.GOVPAAS_SANDBOX_PASSWORD }}
        run: |
          export TF_VAR_paas_app_docker_image=dfedigital/help-for-early-years-providers-sandbox:${{ github.sha }}
          cd terraform/app
          terraform init -reconfigure -input=false -backend-config="bucket=paas-s3-broker-prod-lon-e2222cc7-39c6-44ad-9f24-ca5496b21cae"
          terraform apply -input=false -auto-approve -var-file ../workspace-variables/sandbox.tfvars -var="secret_paas_app_env_values={"RAILS_MASTER_KEY":"${{secrets.RAILS_MASTER_KEY_SANDBOX}}"}' -var 'docker_username=${{ secrets.DOCKER_USERNAME }}' -var 'docker_password=${{ secrets.DOCKER_PASSWORD }}'