name: Delete User

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: dev
      email:
        description: email address of user to destroy
        required: true
        default: ''

jobs:
  delete_user:
    runs-on: ubuntu-20.04
    steps:
      - name: Install CF CLI on Dev
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        if: ${{ github.event.inputs.environment == 'dev' }}
        with:
          CF_USERNAME: ${{ secrets.GOVPAAS_USERNAME }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PASSWORD }}
          CF_SPACE_NAME: eyfs-${{ github.event.inputs.environment }} # required
          # Optional inputs
          CF_CLI_VERSION: v7 # default v7, allowed values: v6 or v7
          CF_ORG_NAME: dfe # default
          CF_API_URL:  https://api.london.cloud.service.gov.uk # default
          INSTALL_CONDUIT: true # default: false

      - name: Install CF CLI on Test
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        if: ${{ github.event.inputs.environment == 'test' }}
        with:
          CF_USERNAME: ${{ secrets.GOVPAAS_USERNAME_TEST }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PASSWORD_TEST }}
          CF_SPACE_NAME: eyfs-${{ github.event.inputs.environment }} # required
          # Optional inputs
          CF_CLI_VERSION: v7 # default v7, allowed values: v6 or v7
          CF_ORG_NAME: dfe # default
          CF_API_URL:  https://api.london.cloud.service.gov.uk # default
          INSTALL_CONDUIT: true # default: false

      - name: Install CF CLI on Pre Prod
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        if: ${{ github.event.inputs.environment == 'pre-prod' }}
        with:
          CF_USERNAME: ${{ secrets.GOVPAAS_USERNAME_PREPROD }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PASSWORD_PREPROD }}
          CF_SPACE_NAME: eyfs-${{ github.event.inputs.environment }} # required
          # Optional inputs
          CF_CLI_VERSION: v7 # default v7, allowed values: v6 or v7
          CF_ORG_NAME: dfe # default
          CF_API_URL:  https://api.london.cloud.service.gov.uk # default
          INSTALL_CONDUIT: true # default: false

      - name: Install CF CLI on Prod
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        if: ${{ github.event.inputs.environment == 'prod' }}
        with:
          CF_USERNAME: ${{ secrets.GOVPAAS_USERNAME_PROD }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PASSWORD_PROD }}
          CF_SPACE_NAME: eyfs-${{ github.event.inputs.environment }} # required
          # Optional inputs
          CF_CLI_VERSION: v7 # default v7, allowed values: v6 or v7
          CF_ORG_NAME: dfe # default
          CF_API_URL:  https://api.london.cloud.service.gov.uk # default
          INSTALL_CONDUIT: true # default: false

      - name: Run delete user task
        run: |
          cf run-task eyfs-${{ github.event.inputs.environment }} --command "cd /app/ && RAILS_ENV=production /usr/local/bin/bundle exec rake sys_admin_tasks:destroy_user['${{ github.event.inputs.email }}']" --name delete-user
