name: Deploy Service Unavailable

on:
  workflow_dispatch:
    inputs:
      confirm_action:
        description: Confirm deploy
        type: boolean
        default: false

jobs:
  deploy-service-unavailable:
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.confirm_action }}
    steps:
      - name: Install CF CLI on Prod
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.GOVPAAS_USERNAME_PROD }}
          CF_PASSWORD: ${{ secrets.GOVPAAS_PASSWORD_PROD }}
          CF_SPACE_NAME: eyfs-prod
          # Optional inputs
          CF_CLI_VERSION: v7 # default v7, allowed values: v6 or v7
          CF_ORG_NAME: dfe # default
          CF_API_URL:  https://api.london.cloud.service.gov.uk # default
          INSTALL_CONDUIT: false # default: false
      - name: make-unavailable
        run: |
          cf target -s eyfs-prod
          cd service_unavailable && cf push
          cf map-route eyfs-service-unavailable education.gov.uk --hostname help-for-early-years-providers
          echo Waiting 5s for route to be registered... && sleep 5
          cf unmap-route eyfs-prod education.gov.uk --hostname help-for-early-years-providers
